/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

import Header from "@components/Header";

import styles from "@styles/Home.module.scss";
import Container from "@components/Container";
import Button from "@components/Button";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.css"
        />
      </Head>

      <Header />

      <main>
        <Container>
          <h1>PlayStation</h1>
          <h2>Available Cards</h2>

          <ul className={styles["products"]}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    width={product.image.width}
                    height={product.image.height}
                    src={product.image.src}
                    alt={`Card for ${product.product_title}`}
                  />
                  <h3 className={styles["productTitle"]}>{product.product_title}</h3>
                  <p className={styles["productPrice"]}>${product.price}</p>
                  <p>
                    <Button
                      className="snipcart-add-item"
                      data-item-id={product.id}
                      data-item-price={product.price}
                      data-item-url="/"
                      data-item-description=""
                      data-item-image={product.image.src}
                      data-item-name={product.product_title}
                    >
                      Add to cart
                    </Button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; PlayStation {new Date().getFullYear()}
      </footer>
      <script
        async
        src="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.js"
      />
      <div
        hidden
        id="snipcart"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_APIKEY}
      />
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://ecommerce-app-test.hasura.app/v1/graphql",
    headers: {
      "x-hasura-admin-secret": process.env.NEXT_HASURA_ADMIN_SECRET
    },
    cache: new InMemoryCache(),
  });

  const response = await client.query({
    query: gql`
      query allProducts {
        products {
          id
          price
          image {
            src
            width
            height
          }
          product_title
        }
      }
    `,
  });

  const products = response.data.products;
  return {
    props: {
      products,
    },
  };
}
