/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

import Container from "@components/Container";
import Button from "@components/Button";
import Layout from "@components/Layout";

import styles from "@styles/Home.module.scss";

export default function Home({ products }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <h1 className="sr-only">PlayStation</h1>
        <h2 className="sr-only">Available Cards</h2>
        <ul className={styles["products"]}>
          {products.map((product) => {
            return (
              <li key={product.id}>
                <Link href={`/products/${product.slug}`}>
                  <a>
                    <div className={styles['product-image']}>
                      <Image
                        width={product.image.width}
                        height={product.image.height}
                        src={product.image.src}
                        alt={`Card for ${product.product_title}`}
                      />
                    </div>
                  </a>
                </Link>
                <h3 className={styles["productTitle"]}>
                  {product.product_title}
                </h3>
                <p className={styles["productPrice"]}>${product.price}</p>
                <p>
                  <Button
                    className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={product.image.src}
                    data-item-name={product.product_title}
                  >
                    Add to cart
                  </Button>
                </p>
              </li>
            );
          })}
        </ul>
      </Container>
    </Layout>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://ecommerce-app-test.hasura.app/v1/graphql",
    headers: {
      "x-hasura-admin-secret": process.env.NEXT_HASURA_ADMIN_SECRET,
    },
    cache: new InMemoryCache(),
  });

  const response = await client.query({
    query: gql`
      query allProducts {
        products(order_by: { id: asc }) {
          id
          price
          slug
          image {
            src
            width
            height
          }
          product_title
        }
      }
    `,
  });

  const products = response.data.products;
  return {
    props: {
      products,
    },
  };
}
